image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - CI=true npm run-script test

deploy:
  stage: deploy
  script:
    - npm install
    - npm run-script build
    - cd server
    - npm install
    - npm run-script compile
    - CI=true npm run-script start
