[context.production.environment]
  REACT_APP_API_URL = "https://api.digitalungdom.se"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://devapi.digitalungdom.se"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://devapi.digitalungdom.se"

[[redirects]]
  from = "https://digitalungdom.se/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://digitalungdom.com/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.digitalungdom.com/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://digitalungdom.net/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.digitalungdom.net/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true
 
[[redirects]]
  from = "https://digitalungdom.org/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.digitalungdom.org/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://digitalungdom.netlify.app/*"
  to = "https://www.digitalungdom.se/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
